sources:
  - name: landing
    database: dbt_project_catalog  
    schema: landing  
    tables:
      - name: orders
        config: 
          freshness:
            warn_after:
              count: 365
              period: day
          loaded_at_field: created_at
        columns:
          - name: id
            data_tests:
              - unique:
                  config: 
                    severity: warn
              - not_null:
                  config: 
                    severity: error              
      - name: products
      - name: reviews
      - name: users
